require('dotenv').config();

module.exports = {
  APP_ENV: process.env.APP_ENV,
  AZURE_STORAGE_CONNECTION_STRING: process.env.AZURE_STORAGE_CONNECTION_STRING,
  COGNITIVE_API_ENDPOINT: process.env.COGNITIVE_API_ENDPOINT,
  COGNITIVE_API_SUBSCRIPTION_KEY: process.env.COGNITIVE_API_SUBSCRIPTION_KEY
};
